name: React App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: ["14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --no-optional --legacy-peer-deps

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: |
          docker build -t abdeljalilelhassani/csa-front .
          docker login -u abdeljalilelhassani -p ${{ secrets.DOCKER_PASSWORD }}
          docker push abdeljalilelhassani/csa-front

      #- name: Deploy to Docker
      #  run: |
      #   docker-compose -f docker-compose.prod.yml up -d
