name: React App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.5.0" # Specify a compatible Node.js version

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install --no-optional --legacy-peer-deps

      - name: Run tests
        run: npm test

      - name: Set up Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: success()
        run: |
          docker build -t abdeljalilelhassani/csa-front:latest .
          docker push abdeljalilelhassani/csa-front:latest

      #- name: Deploy to Docker
      #  run: |
      #   docker-compose -f docker-compose.prod.yml up -d
